apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ingress-cert-reflector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-cert-reflector
  template:
    metadata:
      labels:
        app: ingress-cert-reflector
    spec:
      serviceAccountName: {{ template "ingress-cert-reflector.serviceAccountName" . }}
      containers:
      - name: ns-watch
        image: boxboat/kubectl:latest
        command:
        - sh
        - -c
        - |
          set -e
          while true; do
            echo "$(date '+%Y-%m-%d %H:%M:%S') starting watch loop"
            kubectl get ns --watch --field-selector="status.phase==Active" --no-headers -o "custom-columns=:metadata.name" | \
            while read ns; do
              if [ "$ns" != {{ .Release.Namespace | quote }} ]; then
                echo "$(date '+%Y-%m-%d %H:%M:%S') namespace - $ns"
                kubectl -n {{ .Release.Namespace | quote }} get secret {{ .Values.tls_secret | quote }} -o yaml --export | \
                  kubectl -n "$ns" apply -f -
              fi
            done
          done
      - name: secret-watch
        image: boxboat/kubectl:latest
        command:
        - sh
        - -c
        - |
          set -e
          while true; do
            echo "$(date '+%Y-%m-%d %H:%M:%S') starting watch loop"
            kubectl -n {{ .Release.Namespace | quote }} get secret {{ .Values.tls_secret | quote }} --watch --no-headers -o "custom-columns=:metadata.name" | \
            while read secret; do
              export=$(kubectl -n {{ .Release.Namespace | quote }} get secret "$secret" -o yaml --export)
              for ns in $(kubectl get ns --field-selector="status.phase==Active" --no-headers -o "custom-columns=:metadata.name"); do
                if [ "$ns" != {{ .Release.Namespace | quote }} ]; then
                  echo "$(date '+%Y-%m-%d %H:%M:%S') namespace - $ns"
                  echo "$export" | kubectl -n "$ns" apply -f -
                fi
              done
            done
          done
